[package]
name = "load-dump-derive"
version = "0.1.0"
authors = ["Marco Cilloni <m.c.cilloni@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "*"
quote = "*"
proc-macro2 = "*"
